### ISSUE TITLE
Request for L9 Compatability

### ISSUE THREAD

**Issue by TechnicallyGio** [digit-soft/laravel-swagger-generator#2]
Hi, any idea on L9 compatibility eta?

**Comment by digitv** [comment]
It's already compatible w/ L9.

**Comment by TechnicallyGio** [comment]
[TechnicallyGio](https://github.com/TechnicallyGio) commented [on Mar 4, 2022](https://github.com/digit-soft/laravel-swagger-generator/issues/2#issue-1159347130)
